### ISSUE TITLE
help doc?  or man?

### ISSUE THREAD

**Issue by iateadonut** [Team-Hycon/hycon-core#1]
How do I get to the man or help documentation?  (I've tried 'hycon --help', etc)

**Comment by ghost** [comment]
if its any help
https://medium.com/@teamhycon/so-you-want-to-start-mining-hycon-cde87a4cf58f

**Comment by iateadonut** [comment]
A man/help file should have a list of all arguments that the program takes.

The one I'm looking for specifically is how to use all my CPU cores, usually something like --thread=n.

**Comment by Team-Hycon** [comment]
@iateadonut We're trying to get it all written up in the coming weeks. 

If you're using a release version, edit the `launch` script and change `--cpuMiners=n` to the number of cores you have. Note that bc of cryptonight, the size of your L2 cache will be a constraint to the number of cores being utilized.

**Comment by nowooj** [comment]
You can try it this cmd.

> npm run hycon -- --help
