### ISSUE TITLE
CPU Mining Problem

### ISSUE THREAD

**Issue by zatcha1980** [Team-Hycon/hycon-core#10]
Hi Team,

I'm new to this and ive been trying to sync up to latest block, however i am getting is this problem. I also tried adding peer rapid1.hycon.io:8148 still no go. I have tried closing down window and rebooting laptop still same issue.

![image](https://user-images.githubusercontent.com/38671977/43924492-b68767ee-9c1c-11e8-8a47-4805a638585f.png)

Please help

**Comment by digiuzman** [comment]
You can not because developers only give pool owners fast and stable nodes.. They start to synchronize for a while but u cant solo mining.. Because Only 2 pools have a fully working node version and the team not shared with end-users.

**Comment by Team-Hycon** [comment]
This should no longer be an issue in the latest version
