### ISSUE TITLE
Block Tip Never Seems to Catch up with Header Tip

### ISSUE THREAD

**Issue by riceke** [Team-Hycon/hycon-core#11]
Hello!

Lately (the last couple of weeks or so) it has become very difficult to keep my node in synch with the rest of the network.

I have tried to delete the whole chain and re-synch from scratch but I end up with the same problem: Once the header tip is in synch with the rest of the network the block tip stops advancing. E.g. currently my node has been at block tip 121099 for the last 12 hours but the header tip (currently at 160076) is constantly in synch with the rest of network.

I am currently running the latest version (Gregarious Goose) but the same thing happens even if I downgrade to a previous version.

My node does not have any problems finding peers (usually having 10-20 peers) but it seems that all of the peers either has no higher blocks or are not willing to serve my node with any higher blocks. I have tried several times to delete the peer database but that does not make any difference.

I cannot help feeling that something was changed in the latest release that causes nodes to not serve blocks properly to their peers...

Thanks!

**Comment by digiuzman** [comment]
You can not because developers only give pool owners fast and stable nodes.. They start to synchronize for a while but u cant solo mining.. Because Only 2 pools have a fully working node version and the team not shared with end-users.

**Comment by Team-Hycon** [comment]
@riceke 
Please try adding the launch flag `--peer rapid1.hycon.io:8148` which should serve blocks fairly quickly.

We've been focused on the network side of syncing and have made some great improvements. Block rebroadcast time is now less than 10 ms and a block will typically propagate over the network in less than 3 seconds. Despite these changes it seems that synchronization can still be improved significantly. While profiling the code I noticed that, as the world state database has grown, the time to process new blocks has been growing. We have been experimented with tuning RocksDB, but it seems like the best short term solution would be to prune older information from the worldstate database. We've already implemented the reference counting that is required to identify what information can be pruned, if you would like to read more about pruning [see here](https://blog.ethereum.org/2015/06/26/state-tree-pruning/).

As for a longer term solution we are considering alternatives to the current Merkle Patricia trie, however these would require a hard fork.

Thanks for your patience, and please stay tuned for an update soon,
Owen

**Comment by riceke** [comment]
Hello Owen!

It seems that I may have been a bit too quick to open an issue about this (sorry about that).

It turns out that I have been having issues with my NTP setup, so I had some issues with the time on my machine drifting quite a lot.

I have since fixed my NTP issues and am now re-synchronizing the whole chain again and it all seems to be going smoothly so far.

I will let you know once I am (hopefully) fully synched up again.

Thanks!
