### ISSUE TITLE
Running Out of Memory When Updating Tx Nonce Data

### ISSUE THREAD

**Issue by riceke** [Team-Hycon/hycon-core#13]
Hello!

I just switched to testing version 0.0.9 (for Linux) and it started with updating the transaction database with some additional nonce data. Unfortunately the application runs out of memory and crashes before that operation is completed. My machine is a 64bit AMD with 8GB of RAM, so memory should not really be a problem.

Looking at the crash information it looks like the application has limited itself to using maximum about 1.5GB. Is there a way to tell the node that it is allowed to use more memory, or do I have to download the whole blockchain from scratch again?

Below I have pasted some of the crash information:

[2018-09-06 11:46:10.667] [INFO] TxDB - Since there is no nonce data in the Tx database, updating nonce will be started.

<--- Last few GCs --->

[8500:0x2b8dd00]   256520 ms: Mark-sweep 1383.3 (1438.8) -> 1374.4 (1440.3) MB, 4345.9 / 0.0 ms  (average mu = 0.171, current mu = 0.077) allocation failure scavenge might not succeed
[8500:0x2b8dd00]   260739 ms: Mark-sweep 1384.7 (1440.3) -> 1376.0 (1441.3) MB, 3930.7 / 0.0 ms  (average mu = 0.125, current mu = 0.068) allocation failure scavenge might not succeed

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x255c7ad841bd]
    1: StubFrame [pc: 0x255c7add5afb]
    2: StubFrame [pc: 0x255c7ad8e11c]
Security context: 0x2ff499e1e589 <JSObject>
    3: read_bytes [0x2cfa3bd44889] [/snapshot/rapidphoenix/node_modules/protobufjs/src/reader.js:~299] [pc=0x255c7ade0577](this=0x3c503c507fb1 <BufferReader map = 0x1b7a68782519>)
    4: decode [0x2cfa3bd775b1] [/snapshot/rapidphoenix/build/src/serialization/proto.js:~5076] [pc=0x255...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: node::Abort() [./hycon]
 2: 0x91d94c [./hycon]
 3: v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [./hycon]
 4: v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [./hycon]
 5: 0xe8d332 [./hycon]
 6: v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [./hycon]
 7: v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [./hycon]
 8: v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [./hycon]
 9: v8::internal::Heap::AllocateRawWithRetry(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [./hycon]
10: v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [./hycon]
11: v8::internal::Runtime_AllocateInNewSpace(int, v8::internal::Object**, v8::internal::Isolate*) [./hycon]
12: 0x255c7ad841bd
Aborted

**Comment by riceke** [comment]
Hello!

So, I figured out a way to increase the available memory.

Modifying the 'package.sh' script by adding the option '--options max_old_space_size=4096' to the 'pkg' command will increase the virtual machine memory limit to 4G (in this case) after a rebuild.

Thanks!

**Comment by Team-Hycon** [comment]
Thanks for posting the solution
