### ISSUE TITLE
Block rewards

### ISSUE THREAD

**Issue by datnguyencse** [Team-Hycon/hycon-core#14]
The whitepaper said the the block rewards is 8 HYC for each new block mined. But now there are no rewards for miner for new block mined, only transaction fee.
Am i missing something?

![screenshot from 2018-09-13 16-36-43](https://user-images.githubusercontent.com/11866125/45480452-3b5ef100-b773-11e8-838e-8071114d38ef.png)

**Comment by digiuzman** [comment]
:)

**Comment by nowooj** [comment]
Compensation when one block per second is created.

But, now network make a one block is 30s. So we are paid 8 * 30 HYCON.

If we change to one block per second later, we are paid 8 HYCON.
