### ISSUE TITLE
Unable to Sync Node After Hard Fork

### ISSUE THREAD

**Issue by riceke** [Team-Hycon/hycon-core#18]
Hello!

After the hard fork I am no longer able to get my node synced up. I am running the latest version (0.2.0a) and it always tends to get "stuck" at some block, about a day or so behind the top of the chain, and then the sync just stays at that block for hours (left it once for more than a day and sync still stuck on the same block).

The only way to proceed is for me to go back to an earlier version of the chain and restart from there (I am making a copy of the chain data, before it get stuck, about daily so that I do not have to restart the sync from scratch). When I then restart the sync it will usually continue past the point where it got stuck the last time but eventually again get stuck on another block further down the chain).

It is interesting to note that the block where the sync gets stuck is always a block with at least one uncle.

I have also noted that when the sync seems to be proceeding normally, before it gets stuck, the log will show only syncing of headers, syncing of blocks and rebroadcasting of headers, whereas after the sync is stuck the log will additionally also show processing of block headers while the count of remaining blocks and headers to sync monotonically increases in tandem. 

I have attached a log showing a stretch of almost two hours where the sync seems to start out well and then gets stuck: 

[log.zip](https://github.com/Team-Hycon/hycon-core/files/2680550/log.zip)

Thanks!

**Comment by elniallo** [comment]
Thanks for the comment, we have noticed that there is a small bug in the calculation of the total work in the fork code which is causing these occasional sync issues. We have developed a patch and will release it shortly pending testing. I'll respond again on here once the patch has been published.

**Comment by elniallo** [comment]
Please use version 0.2.0b
