### ISSUE TITLE
Renewed Node Sync Problems After Upgrade to v0.2.0b

### ISSUE THREAD

**Issue by riceke** [Team-Hycon/hycon-core#19]
Hello!

After upgrading my node to version 0.2.0b it was able to sync up nicely and stay in sync for several days.

A few days ago however, the node again started to fall out of sync but this time in a different way. It would seemingly "out of the blue" fall out of sync with the network and start receiving blocks very sparsely (like about once an hour or so) while the number of not synced headers and blocks kept rising steadily.

Rolling back to an earlier backup of the chain data to a couple of days back would start the node off syncing normally but towards the end (after several hours) it would suddenly only pick up a few blocks, having large time intervals between them, and then stop syncing. The interesting part about these last few sparse blocks is that they are all relayed by the same address (i.e. HSMdRFPkPjETsaGGrDqCePPnetyYnGy7).

I have restarted the sync from backups more than a week old several times (over the last days) but it always ends the same way with sync stopping having a bunch of very time-sparse blocks relayed by the address HSMdRFPkPjETsaGGrDqCePPnetyYnGy7.

To me it looks like the node is going off on a branch, created by address HSMdRFPkPjETsaGGrDqCePPnetyYnGy7, and then never manages to get back to the main chain again.

Currently I am stuck and utterly unable to get my node in sync again. Any idea what could be going on? Please note that the node has no shortage of connected peers (some 20 odd peers including rapid.hycon.io).

I have attached a couple of screen shots, showing the list of blocks at the end of the sync, from the "Hycon Blockexplorer" connected to my node. In the first screen shot you will see things starting to go pear shaped and in the second screen shot you see that all the blocks are being relayed only by HSMdRFPkPjETsaGGrDqCePPnetyYnGy7 with large time intervals in between.

![hycon-screenshot-20190101-1](https://user-images.githubusercontent.com/36949352/50576372-2dfc6e00-0e19-11e9-857c-ab8a6000b1dc.png)

![hycon-screenshot-20190101-2](https://user-images.githubusercontent.com/36949352/50576381-4cfb0000-0e19-11e9-8f26-585e70fb597e.png)

Please let me know if you need any additional information from me.

Thanks!

**Comment by riceke** [comment]
Hello!

So, I decided to bite the bullet and throw away the chain data backups and re-sync the whole chain from scratch. It turned out to be quicker than I feared (just a couple of days) as the from scratch sync started from block 404541 rather than from genesis!

Now my node is finally in sync and everything seems to be working fine, so I think you can just close this issue.

Sorry about the apparent "red herring"!

Thanks!

**Comment by elniallo** [comment]
No problem, glad it got sorted
