### ISSUE TITLE
cpu mining problems

### ISSUE THREAD

**Issue by BloupX** [Team-Hycon/hycon-core#6]
Hello to the Hycon team,

I got some problems while mining with cpu on Windows 7.

First i can't find the peer list as it's not showed anymore on Hplorer.com.

When i'm connected to a peer, it start to mine but few minutes later, i got this error
![hycon_bug](https://user-images.githubusercontent.com/40354315/41528066-4e9bfbe2-72e9-11e8-8f2d-0857694b9b89.jpg)

And sometimes, it found blocks quickly, hycon goes on my wallet, and something like 10 minutes laters, all the hycon that i got, dissapears.

Thanks for your help and best regards,

Tony

**Comment by icemanphd** [comment]
you need to turn mining off until you sync to the latest block. Check hplorer.com to see the latest blocks. Your issue is you are mining while you are syncing and it mines on a wrong chain then finds the longer chain and syncs and since you were mining on the wrong chain, your hycon disappear. Only mine once you have synced to an up to date block so you can be sure the hycon you mine is on the right chain and it won't disappear.

**Comment by icemanphd** [comment]
B-tip is best tip and H-tip is high tip.When the H-tip hits the most recent block B-tip will follow up to the number H-tip is. When they both meet is when you are in sync.

**Comment by BloupX** [comment]
Hello,

Thanks for your reply Icemanphd!

Could you please show me an example? i used the launch cmd on their bundle and it start to mine right away.

Thank you!

**Comment by icemanphd** [comment]
@BloupX Sure no problem


Notice in this the b-tip is much lower than the h-tip, if you start mining now, you might mine a shorter chain than the current one and once it finds the correct chain, all the mining you did disappears.  The blockchain isnt updated to the current block. Once b-tip reaches the h-tip is when it has caught up as you can see in the second image below
![mine wait](https://user-images.githubusercontent.com/4239981/41750509-675288c4-758a-11e8-8aa9-1ea86b2a9bc9.png)


Notice in the below screenshot, the b-tip is the same as the h-tip and if you went to hplorer.com at the time I took the screenshot, the most recent block was the same as the b-tip and h-tip. This is when you want to start mining
![mine yes](https://user-images.githubusercontent.com/4239981/41750512-6d233370-758a-11e8-98f8-f9b488617485.png)

**Comment by icemanphd** [comment]
To disable mining please see the screenshot below

![disablemining](https://user-images.githubusercontent.com/4239981/41750812-eab5fa60-758b-11e8-8c2a-6ae6a5cc073d.png)
